-- Criação do banco e tabelas
CREATE DATABASE IF NOT EXISTS imoveis CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE imoveis;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS listings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(200) NOT NULL,
    type ENUM('venda', 'locacao', 'troca') NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    location VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_listings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (name, email, password_hash) VALUES
('Ana Silva 😊', 'ana.silva@example.com', 'hash1'),
('João Pereira 😎', 'joao.pereira@example.com', 'hash2'),
('Maria Oliveira 🌸', 'maria.oliveira@example.com', 'hash3'),
('Carlos Santos 🧱', 'carlos.santos@example.com', 'hash4'),
('Beatriz Costa 🌟', 'beatriz.costa@example.com', 'hash5'),
('Rui Fernandes 🚀', 'rui.fernandes@example.com', 'hash6'),
('Sara Martins 🎨', 'sara.martins@example.com', 'hash7'),
('Miguel Rocha 🏋️‍♂️', 'miguel.rocha@example.com', 'hash8'),
('Patrícia Gomes 💼', 'patricia.gomes@example.com', 'hash9'),
('Tiago Ribeiro ⚽', 'tiago.ribeiro@example.com', 'hash10'),
('Inês Carvalho 🌈', 'ines.carvalho@example.com', 'hash11'),
('Bruno Matos 🔧', 'bruno.matos@example.com', 'hash12'),
('Raquel Dias 🎵', 'raquel.dias@example.com', 'hash13'),
('Pedro Sousa 📚', 'pedro.sousa@example.com', 'hash14'),
('Joana Correia 💐', 'joana.correia@example.com', 'hash15'),
('Nuno Almeida 🍀', 'nuno.almeida@example.com', 'hash16'),
('Helena Duarte 🎬', 'helena.duarte@example.com', 'hash17'),
('André Faria 🛠️', 'andre.faria@example.com', 'hash18'),
('Carolina Pinto 💎', 'carolina.pinto@example.com', 'hash19'),
('Ricardo Lopes 📷', 'ricardo.lopes@example.com', 'hash20'),
('Diana Freitas 🌺', 'diana.freitas@example.com', 'hash21'),
('Hugo Barros 🏎️', 'hugo.barros@example.com', 'hash22'),
('Marta Ribeiro 🧁', 'marta.ribeiro@example.com', 'hash23'),
('Vítor Marques 🔥', 'vitor.marques@example.com', 'hash24'),
('Cátia Neves 🎉', 'catia.neves@example.com', 'hash25'),
('Fábio Mendes 🧩', 'fabio.mendes@example.com', 'hash26'),
('Mariana Lopes 🎈', 'mariana.lopes@example.com', 'hash27'),
('Gustavo Pires 💡', 'gustavo.pires@example.com', 'hash28'),
('Sofia Andrade 🌻', 'sofia.andrade@example.com', 'hash29'),
('Paulo Tavares 🐾', 'paulo.tavares@example.com', 'hash30'),
('Teresa Melo ✨', 'teresa.melo@example.com', 'hash31'),
('Eduardo Nunes 🎯', 'eduardo.nunes@example.com', 'hash32'),
('Filipa Azevedo 💖', 'filipa.azevedo@example.com', 'hash33'),
('Alexandre Cruz 👓', 'alexandre.cruz@example.com', 'hash34'),
('Luísa Matias 🎀', 'luisa.matias@example.com', 'hash35'),
('Rafael Monteiro 🌊', 'rafael.monteiro@example.com', 'hash36'),
('Cláudia Figueiredo 🦋', 'claudia.figueiredo@example.com', 'hash37'),
('Daniel Antunes ❄️', 'daniel.antunes@example.com', 'hash38'),
('Sílvia Ramos 🍎', 'silvia.ramos@example.com', 'hash39'),
('Leonardo Vieira 🎮', 'leonardo.vieira@example.com', 'hash40');

INSERT INTO listings (user_id, title, type, price, location, description) VALUES
(1, 'Apartamento T2 moderno 🏙️', 'venda', 150000, 'Lisboa', 'Apartamento renovado com ótima vista.'),
(2, 'Casa de campo 🌾', 'venda', 230000, 'Viseu', 'Casa espaçosa no campo com jardim.'),
(3, 'Estúdio acolhedor 🛏️', 'locacao', 450, 'Porto', 'Ideal para estudantes.'),
(4, 'Moradia com piscina 🏊‍♂️', 'venda', 390000, 'Braga', 'Piscina privada e garagem.'),
(5, 'T1 perto da praia 🏖️', 'locacao', 800, 'Aveiro', 'A 5 minutos da praia.'),
(6, 'Armazém industrial 🏭', 'venda', 500000, 'Setúbal', 'Ideal para logística.'),
(7, 'Quarto partilhado 🛌', 'locacao', 250, 'Coimbra', 'Despesas incluídas.'),
(8, 'Terreno para construção 🏗️', 'venda', 70000, 'Faro', 'Terreno plano com boa exposição solar.'),
(9, 'Apartamento T3 luminoso 🌞', 'venda', 180000, 'Guimarães', 'Perfeito para famílias.'),
(10, 'Loja comercial 🛍️', 'locacao', 950, 'Lisboa', 'Boa circulação de clientes.'),
(11, 'Moradia geminada 🏡', 'venda', 210000, 'Leiria', 'Zona tranquila.'),
(12, 'Garagem fechada 🚗', 'locacao', 120, 'Porto', 'Espaço amplo.'),
(13, 'Penthouse luxuosa ✨', 'venda', 520000, 'Cascais', 'Vista mar deslumbrante.'),
(14, 'T0 compacto 🧱', 'locacao', 380, 'Évora', 'Bem localizado.'),
(15, 'Apartamento T4 familiar 👨‍👩‍👧‍👦', 'venda', 260000, 'Aveiro', 'Amplas áreas.'),
(16, 'Loja para serviços 💼', 'locacao', 700, 'Braga', 'Ideal para negócios.'),
(17, 'Casa térrea 🌿', 'venda', 185000, 'Santarém', 'Excelente para idosos.'),
(18, 'Armazém pequeno 📦', 'locacao', 400, 'Viana do Castelo', 'Espaço para armazenamento.'),
(19, 'T2 remodelado 🛠️', 'venda', 145000, 'Porto', 'Acabamentos modernos.'),
(20, 'Quarto suite 🛁', 'locacao', 300, 'Lisboa', 'Casa partilhada.'),
(21, 'Vivenda moderna 🏠', 'venda', 350000, 'Sesimbra', 'Varanda ampla.'),
(22, 'Estúdio no centro 🏙️', 'locacao', 500, 'Faro', 'Perto de transportes.'),
(23, 'Casa rústica 🌲', 'venda', 175000, 'Chaves', 'Ambiente rural.'),
(24, 'Apartamento T1 🌇', 'locacao', 550, 'Portimão', 'Ideal para solteiros.'),
(25, 'Terreno agrícola 🚜', 'venda', 45000, 'Beja', 'Bom solo.'),
(26, 'Armazém grande 🏭', 'venda', 650000, 'Lisboa', 'Acesso a camiões.'),
(27, 'T3 novo 🧱', 'venda', 200000, 'Porto', 'Condomínio fechado.'),
(28, 'Casa com quintal 🌻', 'venda', 195000, 'Sintra', 'Espaço exterior amplo.'),
(29, 'Quarto mobilado 🛏️', 'locacao', 320, 'Coimbra', 'Perto da universidade.'),
(30, 'Apartamento T2 clássico 🪟', 'venda', 160000, 'Vila Real', 'Edifício histórico.'),
(31, 'T0 barato 💸', 'locacao', 300, 'Bragança', 'Bom para estudantes.'),
(32, 'Moradia de luxo 💎', 'venda', 720000, 'Cascais', 'Acabamentos premium.'),
(33, 'T1 económico 💰', 'locacao', 400, 'Guarda', 'Bem conservado.'),
(34, 'Escritório moderno 🖥️', 'locacao', 900, 'Lisboa', 'Ideal para startups.'),
(35, 'Apartamento T2 mobiliado 🛋️', 'locacao', 750, 'Setúbal', 'Pronto a habitar.'),
(36, 'Casa com vista mar 🌊', 'venda', 420000, 'Albufeira', 'Vista incrível.'),
(37, 'Garagem dupla 🚗🚗', 'locacao', 150, 'Porto', 'Espaço para 2 carros.'),
(38, 'T3 central 📍', 'venda', 210000, 'Lisboa', 'Excelente localização.'),
(39, 'Armazém médio 📦', 'locacao', 500, 'Faro', 'Bom acesso.'),
(40, 'Loja centro histórico 🏛️', 'locacao', 850, 'Évora', 'Zona turística.');


